emojis = [
    "â¤ï¸",
    "ğŸ’˜",
    "ğŸ’“",
    "ğŸ’•",
    "ğŸ’–",
    "ğŸ’—",
    "ğŸ’™",
    "ğŸ’š",
    "ğŸ’›",
    "ğŸ’œ",
    "ğŸ–¤",
    "ğŸ’",
    "ğŸ’",
    "ğŸ’Ÿ",
    "â£ï¸",
]
channels = [
    198924507472199680,  # pichu enthusiasts
    1033948485914992690, # my test server
]
